sudo: true

language:
  - cpp

compiler:
  - g++

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - lcov

before_install:
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - sudo apt-get update -qq
install:
  - sudo pip install Sphinx sphinx_bootstrap_theme
  - if [ "$CXX" == "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" == "g++" ]; then export CXX="g++-4.8"; fi

script:
  - make
  - ./unit-test

after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "CodeCov Error"
  - cd docs/ && make html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: doc/build/html
  on:
    branch:
      - master
      - development

notifications:
  email: false
