sudo: true

language:
  - cpp

compiler:
  - g++

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - lcov
      - doxygen

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:
  - sudo pip install Sphinx sphinx_bootstrap_theme
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90

script:
  - make
  - ./unit-test

after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "CodeCov Error"
  - doxygen

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs/html
  on:
    branch:
      - master
      - development

notifications:
  email: false
